name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download file
      run: wget https://d36yt3mvayqw5m.cloudfront.net/public/v1.0/can_bus.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: velodyne
        path: ${{ github.workspace }}/*.zip
        retention_days: "15"
