name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_depth_velodyne.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: velodyne
        path: ${{ github.workspace }}/*.zip
        retention_days: "15"
